export const ROUTES = {
  // Root Stacks
  SPLASH: 'SPLASH_SCREEN',
  ONBOARDING: 'ONBOARDING_SCREEN',
  MAIN_TABS: 'MAIN_TABS_NAVIGATOR',

  // Consultation Tab Stack
  CONSULTATION: {
    ROOT: 'CONSULTATION_TAB',
    DOCTOR_LISTING: 'DOCTOR_LISTING_SCREEN',
    DOCTOR_DETAILS: 'DOCTOR_DETAILS_SCREEN',
    SLOT_SELECTION: 'SLOT_SELECTION_SCREEN',
    BOOKING_SUMMARY: 'BOOKING_SUMMARY_SCREEN',
    BOOKING_SUCCESS: 'BOOKING_SUCCESS_SCREEN',
    BOOKING_FAILED: 'BOOKING_FAILED_SCREEN',
    EXPIRED_SLOT: 'EXPIRED_SLOT_SCREEN',
    UPCOMING_CONSULTATIONS: 'UPCOMING_CONSULTATIONS_SCREEN',
  },

  // Shop Tab Stack
  SHOP: {
    ROOT: 'SHOP_TAB',
    PRODUCT_LISTING: 'PRODUCT_LISTING_SCREEN',
    PRODUCT_DETAILS: 'PRODUCT_DETAILS_SCREEN',
    SEARCH_FILTERS: 'SEARCH_FILTERS_SCREEN',
    WISHLIST: 'WISHLIST_SCREEN',
    CART: 'CART_SCREEN',
    CHECKOUT_SUMMARY: 'CHECKOUT_SUMMARY_SCREEN',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS_SCREEN',
  },

  // Health Records Tab Stack
  HEALTH_RECORDS: {
    ROOT: 'HEALTH_RECORDS_TAB',
    TIMELINE: 'RECORD_TIMELINE_SCREEN',
    RECORD_SEARCH: 'RECORD_SEARCH_SCREEN',
    RECORD_DETAILS: 'RECORD_DETAILS_SCREEN',
    IMAGE_PREVIEW: 'IMAGE_PREVIEW_SCREEN',
    PDF_PREVIEW: 'PDF_PREVIEW_SCREEN',
  },

  // Profile & Settings Stack
  PROFILE: {
    ROOT: 'PROFILE_TAB',
    USER_PROFILE: 'USER_PROFILE_SCREEN',
    THEME_SETTINGS: 'THEME_SETTINGS_SCREEN',
    OFFLINE_QUEUE: 'OFFLINE_QUEUE_SCREEN',
    DEVELOPER_SETTINGS: 'DEVELOPER_SETTINGS_SCREEN',
  },
} as const;
